name: Update GitHub Pages with READMEs

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs daily

permissions:
  contents: write  # Needed to push changes (if necessary)

jobs:
  fetch-readmes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # Prevents commit issues

      - name: Authenticate GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh auth status

      - name: Fetch READMEs Without Storing in Repo
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p /tmp/readmes
          echo "Fetching repositories..."
          gh repo list readme-hub-test --json name -q '.[].name' > repos.txt

          while read repo; do
            echo "Fetching README from $repo..."
            gh api repos/readme-hub-test/$repo/readme --header "Accept: application/vnd.github.raw" > /tmp/readmes/$repo.md || echo "No README found" > /tmp/readmes/$repo.md
          done < repos.txt

      - name: Serve READMEs in Jekyll
        run: |
          mkdir -p _site
          cp -r /tmp/readmes _site/readmes  # Copy readmes for Jekyll to use

      - name: Deploy GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site  # Deploy only the generated site
