name: Update GitHub Pages with READMEs

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  fetch-readmes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: sudo apt install -y jq gh

      - name: Authenticate GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh auth status
      
      - name: Fetch READMEs from All Repos
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p _includes
          echo "Fetching repositories..."
          gh repo list YOUR_ORG --json name -q '.[].name' > repos.txt
      
          while read repo; do
            echo "Fetching README from $repo..."
            gh api repos/YOUR_ORG/$repo/readme --header "Accept: application/vnd.github.raw" > _includes/$repo.md || echo "No README found" > _includes/$repo.md
          done < repos.txt

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add _includes/*
          git commit -m "Update READMEs" || echo "No changes to commit"
          git push origin main
